doctrine:
    dbal:
        driver: 'pdo_pgsql' # Utilisation du pilote PostgreSQL
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        # Configurez la version du serveur si nécessaire
        # server_version: '12' # Spécifiez la version du serveur PostgreSQL si nécessaire
        # Utilisez le pooling de connexions pour améliorer les performances
        # pooling: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
