<?php

namespace ContainerTZRaAaE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ur9f.YA.App\Controller\RoleController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ur9f.YA.App\\Controller\\RoleController::index()'] = ($container->privates['.service_locator.Ur9f.YA'] ?? $container->load('get_ServiceLocator_Ur9f_YAService'))->withContext('App\\Controller\\RoleController::index()', $container);
    }
}
