# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\CustomAuthenticator:
        arguments:
            $userProvider: '@security.user.provider.concrete.user_provider'
            $demandeurProvider: '@security.user.provider.concrete.demandeur_provider'
