<?php

namespace ContainerEbaaRGu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5NfVtKvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5NfVtKv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5NfVtKv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['privates', '.errored..service_locator.5NfVtKv.Symfony\\Bridge\\Doctrine\\ManagerRegistry', NULL, 'Cannot autowire service ".service_locator.5NfVtKv": it references class "Symfony\\Bridge\\Doctrine\\ManagerRegistry" but no such service exists. Try changing the type-hint to "Doctrine\\Persistence\\ManagerRegistry" instead.'],
        ], [
            'doctrine' => 'Symfony\\Bridge\\Doctrine\\ManagerRegistry',
        ]);
    }
}
