<?php

namespace ContainerEbaaRGu;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoleControlleraddRoleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5NfVtKv.App\Controller\RoleController::addRole()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5NfVtKv.App\\Controller\\RoleController::addRole()'] = ($container->privates['.service_locator.5NfVtKv'] ?? $container->load('get_ServiceLocator_5NfVtKvService'))->withContext('App\\Controller\\RoleController::addRole()', $container);
    }
}
