<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTZRaAaE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTZRaAaE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTZRaAaE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTZRaAaE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTZRaAaE\App_KernelDevDebugContainer([
    'container.build_hash' => 'TZRaAaE',
    'container.build_id' => 'efd1aa58',
    'container.build_time' => 1722813262,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTZRaAaE');
