<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUq8MVH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUq8MVH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTUq8MVH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTUq8MVH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTUq8MVH\App_KernelDevDebugContainer([
    'container.build_hash' => 'TUq8MVH',
    'container.build_id' => 'eff68175',
    'container.build_time' => 1720983338,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUq8MVH');
