<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNntRXQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNntRXQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNntRXQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNntRXQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPNntRXQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PNntRXQ',
    'container.build_id' => 'd9742e84',
    'container.build_time' => 1720718691,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNntRXQ');
